name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '39 20 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: pip
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        PAT: ${{ secrets.PAT }}
      run: |-
        python most_recent_til_blogs.py
        python most_recent_releases.py
        cat README.md
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
